var mobs={
    "H₂":{
        "atk":50,
        "asset":'<i class="fa fa-burn"></i>',
        "hp":250,
        "drop":[
            {"prob":0.1,"petal":"H₂","lvl":-2},
            {"prob":0.25,"petal":"H₂","lvl":-1},
            {"prob":0.5,"petal":"H₂","lvl":0},
            {"prob":0.2,"petal":"N₂","lvl":0},
            {"prob":0.2,"petal":"NO₂","lvl":0},
            {"prob":0.3,"petal":"D₂O","lvl":0}
        ],
        "vel":0,
        "gen":[],
        "tag":["basic"]
    },
    "H₂-0":{},
    "H₂-1":{},
    "H₂-2":{"vel":0.25},
    "H₂-3":{"vel":0.5},
    "H₂-4":{"vel":0.7},
    "H₂-5":{"vel":1.0},
    "H₂-6":{"vel":1.5},
    "H₂-8":{
        "vel":2.5,
        "overwritedrop":[]
    },
    "O₂":{
        "atk":10,
        "asset":'<i class="fa-regular fa-circle"></i>',
        "hp":500,
        "drop":[
            {"prob":0.1,"petal":"O₂","lvl":-2},
            {"prob":0.25,"petal":"O₂","lvl":-1},
            {"prob":0.5,"petal":"O₂","lvl":0},
            {"prob":0.5,"petal":"KMnO₄","lvl":0},
            {"prob":0.2,"petal":"N₂","lvl":0},
            {"prob":0.2,"petal":"NO₂","lvl":0}
        ],
        "vel":0,
        "gen":[],
        "tag":["basic"]
    },
    "O₂-0":{},
    "O₂-1":{},
    "O₂-2":{},
    "O₂-3":{},
    "O₂-4":{},
    "O₂-5":{},
    "O₂-6":{},
    "CaCO₃":{
        "atk":5,
        "asset":'<i class="fa fa-bowling-ball"></i>',
        "hp":750,
        "drop":[
            {"prob":0.1,"petal":"CaCO₃","lvl":-2},
            {"prob":0.25,"petal":"CaCO₃","lvl":-1},
            {"prob":0.5,"petal":"CaCO₃","lvl":0},
            {"prob":0.1,"petal":"SiO₂","lvl":-2},
            {"prob":0.25,"petal":"SiO₂","lvl":-1},
            {"prob":0.5,"petal":"SiO₂","lvl":0},
            {"prob":0.1,"petal":"Nd","lvl":-2},
            {"prob":0.25,"petal":"Nd","lvl":-1},
            {"prob":0.5,"petal":"Nd","lvl":0},
            {"prob":0.1,"petal":"Fe₃O₄","lvl":-2},
            {"prob":0.25,"petal":"Fe₃O₄","lvl":-1},
            {"prob":0.5,"petal":"Fe₃O₄","lvl":0},
            {"prob":0.1,"petal":"Na","lvl":-2},
            {"prob":0.25,"petal":"Na","lvl":-1},
            {"prob":0.5,"petal":"Na","lvl":0},
            {"prob":0.1,"petal":"Pb","lvl":-2},
            {"prob":0.25,"petal":"Pb","lvl":-1},
            {"prob":0.5,"petal":"Pb","lvl":0},
            {"prob":0.1,"petal":"Bi","lvl":-2},
            {"prob":0.25,"petal":"Bi","lvl":-1},
            {"prob":0.5,"petal":"Bi","lvl":0},
            {"prob":0.1,"petal":"¹³⁷Cs","lvl":-2},
            {"prob":0.25,"petal":"¹³⁷Cs","lvl":-1},
            {"prob":0.5,"petal":"¹³⁷Cs","lvl":0}
        ],
        "vel":0,
        "gen":[],
        "tag":["basic"]
    },
    "CaCO₃-0":{},
    "CaCO₃-1":{},
    "CaCO₃-2":{},
    "CaCO₃-3":{},
    "CaCO₃-4":{},
    "CaCO₃-5":{},
    "HNO₃":{
        "atk":100,
        "asset":'<i class="fa-solid fa-flask-vial"></i>',
        "hp":20,
        "drop":[
            {"prob":0.1,"petal":"HNO₃","lvl":-2},
            {"prob":0.25,"petal":"HNO₃","lvl":-1},
            {"prob":0.5,"petal":"HNO₃","lvl":0},
            {"prob":0.1,"petal":"HNO₂","lvl":0},
            {"prob":0.1,"petal":"D₂O","lvl":0}
        ],
        "vel":0.1,
        "gen":[],
        "tag":["basic"]
    },
    "HNO₃-0":{"vel":0.1},
    "HNO₃-1":{"vel":0.2},
    "HNO₃-2":{"vel":0.3},
    "HNO₃-3":{"vel":0.5},
    "HNO₃-4":{"vel":0.75},
    "HNO₃-5":{"vel":1},
    "HNO₃-6":{"vel":2},
    "HNO₃-8":{
        "vel":3,
        "overwritedrop":[]
    },
    "He":{
        "atk":10,
        "asset":'<i class="fa fa-lightbulb"></i>',
        "hp":100,
        "drop":[
            {"prob":0.1,"petal":"He","lvl":-2},
            {"prob":0.25,"petal":"He","lvl":-1},
            {"prob":0.5,"petal":"He","lvl":0},
            {"prob":0.1,"petal":"HHe⁺","lvl":0},
            {"prob":0.2,"petal":"N₂","lvl":0},
            {"prob":0.2,"petal":"NO₂","lvl":0}
        ],
        "vel":-0.1,
        "gen":[],
        "tag":["rare"]
    },
    "He-0":{},
    "He-1":{},
    "He-2":{},
    "He-3":{},
    "He-4":{},
    "He-5":{},
    "He-6":{},
    "NH₃":{
        "atk":1,
        "asset":'<i class="fa fa-smog"></i>',
        "hp":100,
        "drop":[
            {"prob":0.1,"petal":"NH₃","lvl":-2},
            {"prob":0.25,"petal":"NH₃","lvl":-1},
            {"prob":0.5,"petal":"NH₃","lvl":0}
        ],
        "vel":2,
        "gen":[],
        "tag":["rare"]
    },
    "NH₃-0":{"vel":2},
    "NH₃-1":{"vel":2.1},
    "NH₃-2":{"vel":2.2},
    "NH₃-3":{"vel":2.3},
    "NH₃-4":{"vel":2.4},
    "NH₃-5":{"vel":2.5},
    "NH₃-6":{"vel":2.6},
    "NH₃-8":{
        "vel":3,
        "overwritedrop":[]
    },
    "²³⁵U":{
        "atk":10,
        "asset":'<i class="fa-solid fa-atom"></i>',
        "hp":300,
        "drop":[
            {"prob":0.1,"petal":"²³⁵U","lvl":-2},
            {"prob":0.25,"petal":"²³⁵U","lvl":-1},
            {"prob":0.5,"petal":"²³⁵U","lvl":0},
            {"prob":0.1,"petal":"Nd","lvl":-2},
            {"prob":0.25,"petal":"Nd","lvl":-1},
            {"prob":0.5,"petal":"Nd","lvl":0},
            {"prob":0.1,"petal":"Bi","lvl":-2},
            {"prob":0.25,"petal":"Bi","lvl":-1},
            {"prob":0.5,"petal":"Bi","lvl":0},
            {"prob":0.1,"petal":"²³⁹Pu","lvl":0},
            {"prob":0.1,"petal":"¹³⁷Cs","lvl":-2},
            {"prob":0.25,"petal":"¹³⁷Cs","lvl":-1},
            {"prob":0.5,"petal":"¹³⁷Cs","lvl":0},
            {"prob":0.1,"petal":"D₂O","lvl":-2},
            {"prob":0.25,"petal":"D₂O","lvl":-1},
            {"prob":0.5,"petal":"D₂O","lvl":0}
        ],
        "vel":0,
        "gen":[
            {
                "cd":150,
                "lvl":0,
                "name":"n",
                "atk":5,
                "life":1000,
                "vel":2
            }
        ],
        "tag":["radioactive"]
    },
    "²³⁵U-0":{},
    "²³⁵U-1":{},
    "²³⁵U-2":{},
    "²³⁵U-3":{},
    "²³⁵U-4":{},
    "²³⁵U-5":{},
    "²³⁵U-6":{},
    "CuSO₄":{
        "atk":1,
        "asset":'<i class="fa-solid fa-gem"></i>',
        "hp":500,
        "drop":[
            {"prob":0.1,"petal":"CuSO₄","lvl":-2},
            {"prob":0.25,"petal":"CuSO₄","lvl":-1},
            {"prob":0.5,"petal":"CuSO₄","lvl":0},
            {"prob":0.01,"petal":"<span style='color:blue'>V</span>","lvl":0},
            {"prob":0.001,"petal":"<span style='color:yellow'>φ</span>","lvl":0},
            {"prob":0.2,"petal":"D₂O","lvl":0}
        ],
        "vel":0,
        "gen":[],
        "tag":["rare"]
    },
    "CuSO₄-0":{},
    "CuSO₄-1":{},
    "CuSO₄-2":{},
    "CuSO₄-3":{},
    "CuSO₄-4":{},
    "CuSO₄-5":{},
    "CuSO₄-6":{},
    "³H":{
        "atk":7,
        "asset":'<i class="fa-solid fa-atom"></i>',
        "hp":50,
        "drop":[
            {"prob":0.1,"petal":"H₂","lvl":-2},
            {"prob":0.25,"petal":"H₂","lvl":-1},
            {"prob":0.5,"petal":"H₂","lvl":0},
            {"prob":0.1,"petal":"D₂O","lvl":-2},
            {"prob":0.25,"petal":"D₂O","lvl":-1},
            {"prob":0.5,"petal":"D₂O","lvl":0}
        ],
        "vel":1,
        "gen":[
            {
                "cd":150,
                "lvl":0,
                "name":"e⁺",
                "atk":1,
                "life":1000,
                "vel":3,
                "cust_movement_func":function(cur){
                    var dir=Math.atan2(cur.x-x,cur.y-y);
                    var vel=Math.sqrt(cur.vx**2+cur.vy**2);
                    var vx=-vel*Math.sin(dir);
                    var vy=-vel*Math.cos(dir);
                    return {
                        "x":cur.x+vx,
                        "y":cur.y+vy,
                        "vx":vx,
                        "vy":vy
                    };
                }
            }
        ],
        "tag":["radioactive"]
    },
    "³H-0":{},
    "³H-1":{},
    "³H-2":{},
    "³H-3":{},
    "³H-4":{},
    "³H-5":{},
    "Cs":{
        "tag":["boss"],
        "gen":[
            {
                "cd":200,
                "lvl":0,
                "name":"e⁻",
                "atk":1,
                "life":1000,
                "vel":2
            }
        ]
    },
    "Cs-7":{
        "atk":114514,
        "asset":'<i class="fa-solid fa-atom"></i>',
        "hp":1145140,
        "drop":[
            {"prob":0.2,"petal":"H₂","lvl":7},
            {"prob":0.2,"petal":"O₂","lvl":7},
            {"prob":0.2,"petal":"HNO₃","lvl":7},
            {"prob":0.2,"petal":"CaCO₃","lvl":7},
            {"prob":0.1,"petal":"LiOH","lvl":8},
            {"prob":0.2,"petal":"SiO₂","lvl":7},
            // {"prob":0.2,"petal":"NH₃","lvl":7}
        ],
        "vel":2
    },
    "Cs-8":{
        "atk":1919810,
        "asset":'<i class="fa-solid fa-atom" />',
        "hp":19198100,
        "drop":[
            {"prob":0.2,"petal":"H₂","lvl":8},
            {"prob":0.2,"petal":"O₂","lvl":8},
            {"prob":0.2,"petal":"HNO₃","lvl":8},
            {"prob":0.2,"petal":"CaCO₃","lvl":8},
            {"prob":0.1,"petal":"LiOH","lvl":8},
            {"prob":0.2,"petal":"SiO₂","lvl":8},
            {"prob":0.01,"petal":"↑+++","lvl":8},
            {"prob":0.01,"petal":"e⁻","lvl":0}
        ],
        "vel":2.1
    },
    "H₂SO₃":{
        "atk":0,
        "asset":'<i class="fa-solid fa-flask-vial"></i>',
        "hp":0.0001,
        "drop":[
            {"prob":0.5,"petal":"HNO₂","lvl":0},
            {"prob":0.5,"petal":"↑+++","lvl":0}
        ],
        "vel":5,
        "gen":[],
        "tag":["whr"]
    },
    "H₂SO₃-8":{},
    "Fr":{
        "asset":'<i class="fa-solid fa-atom"></i>',
        "drop":[],
        "tag":["final-boss"],
        "vel":0,
        "gen":[
            {
                "cd":100,
                "lvl":0,
                "name":"n",
                "atk":5,
                "life":1000,
                "vel":2
            }
        ]
    },
    "Fr-8":{
        "atk":2147483647,
        "hp":1145141919810,
        "overwritedrop":[
            {"prob":1,"petal":"e⁻","lvl":0},
            {"prob":1,"petal":"H₂","lvl":8},
            {"prob":1,"petal":"O₂","lvl":8},
            {"prob":1,"petal":"CaCO₃","lvl":8},
            {"prob":1,"petal":"HNO₃","lvl":8},
            {"prob":0.05,"petal":"H₂CO₃","lvl":8},
            {"prob":1,"petal":"KMnO₄","lvl":8},
            {"prob":1,"petal":"LiOH","lvl":8},
            {"prob":0.5,"petal":"HNO₂","lvl":8},
            {"prob":1,"petal":"He","lvl":8},
            {"prob":1,"petal":"NH₃","lvl":8},
            {"prob":0.1,"petal":"?","lvl":0},
            {"prob":0.1,"petal":"?","lvl":1},
            {"prob":0.1,"petal":"?","lvl":2},
            {"prob":0.1,"petal":"?","lvl":3},
            {"prob":0.1,"petal":"?","lvl":4},
            {"prob":0.1,"petal":"?","lvl":5},
            {"prob":0.1,"petal":"?","lvl":6},
            {"prob":0.1,"petal":"?","lvl":7},
            {"prob":1,"petal":"SiO₂","lvl":8},
            {"prob":0.5,"petal":"HHe⁺","lvl":8},
            {"prob":1,"petal":"CuSO₄","lvl":8},
            {"prob":0.3,"petal":"↑+++","lvl":8},
            {"prob":0.1,"petal":"<span style='color:blue'>V</span>","lvl":8},
            {"prob":0.05,"petal":"<span style='color:yellow'>φ</span>","lvl":8},
            {"prob":1,"petal":"Nd","lvl":8},
            {"prob":1,"petal":"Fe₃O₄","lvl":8},
            {"prob":1,"petal":"N₂","lvl":8},
            {"prob":1,"petal":"NO₂","lvl":8},
            {"prob":1,"petal":"Na","lvl":8},
            {"prob":1,"petal":"²³⁵U","lvl":8},
            {"prob":0.5,"petal":"D₂O","lvl":8},
			{"prob":0.5,"petal":"Uue","lvl":8}
        ]
    },
    "Uue":{
        "asset":'<i class="fa-solid fa-atom"></i>',
        "drop":[],
        "tag":["ultra-final-boss"],
        "vel":0,
        "gen":[
            {
                "cd":50,
                "lvl":0,
                "name":"n",
                "atk":10,
                "life":1000,
                "vel":2
            },
            {
                "cd":100,
                "lvl":0,
                "name":"n",
                "atk":5,
                "life":1000,
                "vel":2,
                "delta":-0.15
            },
            {
                "cd":100,
                "lvl":0,
                "name":"n",
                "atk":5,
                "life":1000,
                "vel":2,
                "delta":0.15
            }
        ]
    },
    "Uue-8":{
        "atk":2147483647,
        "hp":114514191981000,
        "overwritedrop":[
            {"prob":1,"petal":"H₂","lvl":8},
            {"prob":1,"petal":"O₂","lvl":8},
            {"prob":1,"petal":"CaCO₃","lvl":8},
            {"prob":1,"petal":"HNO₃","lvl":8},
            {"prob":0.05,"petal":"H₂CO₃","lvl":8},
            {"prob":1,"petal":"KMnO₄","lvl":8},
            {"prob":1,"petal":"LiOH","lvl":8},
            {"prob":0.5,"petal":"HNO₂","lvl":8},
            {"prob":1,"petal":"He","lvl":8},
            {"prob":1,"petal":"NH₃","lvl":8},
            {"prob":0.1,"petal":"?","lvl":0},
            {"prob":0.1,"petal":"?","lvl":1},
            {"prob":0.1,"petal":"?","lvl":2},
            {"prob":0.1,"petal":"?","lvl":3},
            {"prob":0.1,"petal":"?","lvl":4},
            {"prob":0.1,"petal":"?","lvl":5},
            {"prob":0.1,"petal":"?","lvl":6},
            {"prob":0.1,"petal":"?","lvl":7},
            {"prob":1,"petal":"SiO₂","lvl":8},
            {"prob":0.5,"petal":"HHe⁺","lvl":8},
            {"prob":1,"petal":"CuSO₄","lvl":8},
            {"prob":0.3,"petal":"↑+++","lvl":8},
            {"prob":0.1,"petal":"<span style='color:blue'>V</span>","lvl":8},
            {"prob":0.05,"petal":"<span style='color:yellow'>φ</span>","lvl":8},
            {"prob":1,"petal":"Nd","lvl":8},
            {"prob":1,"petal":"Fe₃O₄","lvl":8},
            {"prob":1,"petal":"N₂","lvl":8},
            {"prob":1,"petal":"NO₂","lvl":8},
            {"prob":1,"petal":"Na","lvl":8},
            {"prob":1,"petal":"²³⁵U","lvl":8},
            {"prob":0.5,"petal":"D₂O","lvl":8},
            {"prob":1,"petal":"H₂","lvl":8},
            {"prob":1,"petal":"O₂","lvl":8},
            {"prob":1,"petal":"CaCO₃","lvl":8},
            {"prob":1,"petal":"HNO₃","lvl":8},
            {"prob":0.05,"petal":"H₂CO₃","lvl":8},
            {"prob":1,"petal":"KMnO₄","lvl":8},
            {"prob":1,"petal":"LiOH","lvl":8},
            {"prob":0.5,"petal":"HNO₂","lvl":8},
            {"prob":1,"petal":"He","lvl":8},
            {"prob":1,"petal":"NH₃","lvl":8},
            {"prob":0.1,"petal":"?","lvl":0},
            {"prob":0.1,"petal":"?","lvl":1},
            {"prob":0.1,"petal":"?","lvl":2},
            {"prob":0.1,"petal":"?","lvl":3},
            {"prob":0.1,"petal":"?","lvl":4},
            {"prob":0.1,"petal":"?","lvl":5},
            {"prob":0.1,"petal":"?","lvl":6},
            {"prob":0.1,"petal":"?","lvl":7},
            {"prob":1,"petal":"SiO₂","lvl":8},
            {"prob":0.5,"petal":"HHe⁺","lvl":8},
            {"prob":1,"petal":"CuSO₄","lvl":8},
            {"prob":0.3,"petal":"↑+++","lvl":8},
            {"prob":0.1,"petal":"<span style='color:blue'>V</span>","lvl":8},
            {"prob":0.05,"petal":"<span style='color:yellow'>φ</span>","lvl":8},
            {"prob":1,"petal":"Nd","lvl":8},
            {"prob":1,"petal":"Fe₃O₄","lvl":8},
            {"prob":1,"petal":"N₂","lvl":8},
            {"prob":1,"petal":"NO₂","lvl":8},
            {"prob":1,"petal":"Na","lvl":8},
            {"prob":1,"petal":"²³⁵U","lvl":8},
            {"prob":0.5,"petal":"D₂O","lvl":8},
            {"prob":1,"petal":"H₂","lvl":8},
            {"prob":1,"petal":"O₂","lvl":8},
            {"prob":1,"petal":"CaCO₃","lvl":8},
            {"prob":1,"petal":"HNO₃","lvl":8},
            {"prob":0.05,"petal":"H₂CO₃","lvl":8},
            {"prob":1,"petal":"KMnO₄","lvl":8},
            {"prob":1,"petal":"LiOH","lvl":8},
            {"prob":0.5,"petal":"HNO₂","lvl":8},
            {"prob":1,"petal":"He","lvl":8},
            {"prob":1,"petal":"NH₃","lvl":8},
            {"prob":0.1,"petal":"?","lvl":0},
            {"prob":0.1,"petal":"?","lvl":1},
            {"prob":0.1,"petal":"?","lvl":2},
            {"prob":0.1,"petal":"?","lvl":3},
            {"prob":0.1,"petal":"?","lvl":4},
            {"prob":0.1,"petal":"?","lvl":5},
            {"prob":0.1,"petal":"?","lvl":6},
            {"prob":0.1,"petal":"?","lvl":7},
            {"prob":1,"petal":"SiO₂","lvl":8},
            {"prob":0.5,"petal":"HHe⁺","lvl":8},
            {"prob":1,"petal":"CuSO₄","lvl":8},
            {"prob":0.3,"petal":"↑+++","lvl":8},
            {"prob":0.1,"petal":"<span style='color:blue'>V</span>","lvl":8},
            {"prob":0.05,"petal":"<span style='color:yellow'>φ</span>","lvl":8},
            {"prob":1,"petal":"Nd","lvl":8},
            {"prob":1,"petal":"Fe₃O₄","lvl":8},
            {"prob":1,"petal":"N₂","lvl":8},
            {"prob":1,"petal":"NO₂","lvl":8},
            {"prob":1,"petal":"Na","lvl":8},
            {"prob":1,"petal":"²³⁵U","lvl":8},
            {"prob":0.5,"petal":"D₂O","lvl":8},
            {"prob":1,"petal":"H₂","lvl":8},
            {"prob":1,"petal":"O₂","lvl":8},
            {"prob":1,"petal":"CaCO₃","lvl":8},
            {"prob":1,"petal":"HNO₃","lvl":8},
            {"prob":0.05,"petal":"H₂CO₃","lvl":8},
            {"prob":1,"petal":"KMnO₄","lvl":8},
            {"prob":1,"petal":"LiOH","lvl":8},
            {"prob":0.5,"petal":"HNO₂","lvl":8},
            {"prob":1,"petal":"He","lvl":8},
            {"prob":1,"petal":"NH₃","lvl":8},
            {"prob":0.1,"petal":"?","lvl":0},
            {"prob":0.1,"petal":"?","lvl":1},
            {"prob":0.1,"petal":"?","lvl":2},
            {"prob":0.1,"petal":"?","lvl":3},
            {"prob":0.1,"petal":"?","lvl":4},
            {"prob":0.1,"petal":"?","lvl":5},
            {"prob":0.1,"petal":"?","lvl":6},
            {"prob":0.1,"petal":"?","lvl":7},
            {"prob":1,"petal":"SiO₂","lvl":8},
            {"prob":0.5,"petal":"HHe⁺","lvl":8},
            {"prob":1,"petal":"CuSO₄","lvl":8},
            {"prob":0.3,"petal":"↑+++","lvl":8},
            {"prob":0.1,"petal":"<span style='color:blue'>V</span>","lvl":8},
            {"prob":0.05,"petal":"<span style='color:yellow'>φ</span>","lvl":8},
            {"prob":1,"petal":"Nd","lvl":8},
            {"prob":1,"petal":"Fe₃O₄","lvl":8},
            {"prob":1,"petal":"N₂","lvl":8},
            {"prob":1,"petal":"NO₂","lvl":8},
            {"prob":1,"petal":"Na","lvl":8},
            {"prob":1,"petal":"²³⁵U","lvl":8},
            {"prob":0.5,"petal":"D₂O","lvl":8},
            {"prob":1,"petal":"H₂","lvl":8},
            {"prob":1,"petal":"O₂","lvl":8},
            {"prob":1,"petal":"CaCO₃","lvl":8},
            {"prob":1,"petal":"HNO₃","lvl":8},
            {"prob":0.05,"petal":"H₂CO₃","lvl":8},
            {"prob":1,"petal":"KMnO₄","lvl":8},
            {"prob":1,"petal":"LiOH","lvl":8},
            {"prob":0.5,"petal":"HNO₂","lvl":8},
            {"prob":1,"petal":"He","lvl":8},
            {"prob":1,"petal":"NH₃","lvl":8},
            {"prob":0.1,"petal":"?","lvl":0},
            {"prob":0.1,"petal":"?","lvl":1},
            {"prob":0.1,"petal":"?","lvl":2},
            {"prob":0.1,"petal":"?","lvl":3},
            {"prob":0.1,"petal":"?","lvl":4},
            {"prob":0.1,"petal":"?","lvl":5},
            {"prob":0.1,"petal":"?","lvl":6},
            {"prob":0.1,"petal":"?","lvl":7},
            {"prob":1,"petal":"SiO₂","lvl":8},
            {"prob":0.5,"petal":"HHe⁺","lvl":8},
            {"prob":1,"petal":"CuSO₄","lvl":8},
            {"prob":0.3,"petal":"↑+++","lvl":8},
            {"prob":0.1,"petal":"<span style='color:blue'>V</span>","lvl":8},
            {"prob":0.05,"petal":"<span style='color:yellow'>φ</span>","lvl":8},
            {"prob":1,"petal":"Nd","lvl":8},
            {"prob":1,"petal":"Fe₃O₄","lvl":8},
            {"prob":1,"petal":"N₂","lvl":8},
            {"prob":1,"petal":"NO₂","lvl":8},
            {"prob":1,"petal":"Na","lvl":8},
            {"prob":1,"petal":"²³⁵U","lvl":8},
            {"prob":0.5,"petal":"D₂O","lvl":8},
            {"prob":1,"petal":"e⁻","lvl":2},
            {"prob":0.5,"petal":"e⁻","lvl":3},
            {"prob":0.1,"petal":"e⁻","lvl":4},
        ]
    }
};
var mob_profile={};
for(var mob in mobs){
    if(mob.indexOf("-")==-1){
        mob_profile[mob]=mobs[mob];
    }
}
for(var mob in mobs){
    if(mob.indexOf("-")!=-1){
        var lvl=parseInt(mob.split("-")[1]);
        var mobid=mob.split("-")[0];
        if(mobs[mob].atk==undefined)mobs[mob].atk=mob_profile[mobid].atk*3**lvl;
        if(mobs[mob].hp==undefined)mobs[mob].hp=mob_profile[mobid].hp*3**lvl;
        if(mobs[mob].asset==undefined)mobs[mob].asset=mob_profile[mobid].asset;
        if(mobs[mob].drop==undefined){
            mobs[mob].drop=[];
            for(var i=0;i<mob_profile[mobid].drop.length;i++){
                var dat=mob_profile[mobid].drop[i];
                if(lvl+dat.lvl>=0&&lvl+dat.lvl<=8)mobs[mob].drop.push({"prob":dat.prob*(0.9)**lvl,"petal":dat.petal,"lvl":lvl+dat.lvl});
            }
        }
        if(mobs[mob].overwritedrop!=undefined)mobs[mob].drop=mobs[mob].overwritedrop;
        mobs[mob].gen=[];
        if(mob_profile[mobid].gen){
            for(var i=0;i<mob_profile[mobid].gen.length;i++){
                var data=mob_profile[mobid].gen[i];
                if(lvl+data.lvl>=0&&lvl+data.lvl<=8){
                    mobs[mob].gen.push({
                        "cd":data.cd,
                        "lvl":lvl+data.lvl,
                        "name":data.name,
                        "atk":data.atk*3**lvl,
                        "is_player":false,
                        "life":data.life,
                        "vel":data.vel*(1.25)**lvl,
                        "delta":data.delta||0,
                        "cust_movement_func":data.cust_movement_func
                    });
                }
            }
        }
        if(mobs[mob].vel==undefined)mobs[mob].vel=mob_profile[mobid].vel;
        mobs[mob].tag=mob_profile[mobid].tag;
    }
}
